# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 8.6.10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build

  test-coverage:
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      contents: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup pnpm
          # You may pin to the exact commit or the version.
          # uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
          uses: pnpm/action-setup@v3.0.0
          with:
            version: 8.6.10
        - uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            package-manager: pnpm
            test-script: pnpm test

